/*
 * ONDC Registry 
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OndcRegistry_);
  }
}(this, function(expect, OndcRegistry_) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VlookupSellerOnRecord', function() {
      beforeEach(function() {
        instance = new OndcRegistry_.VlookupSellerOnRecord();
      });

      it('should create an instance of VlookupSellerOnRecord', function() {
        // TODO: update the code to test VlookupSellerOnRecord
        expect(instance).to.be.a(OndcRegistry_.VlookupSellerOnRecord);
      });

      it('should have the property uniqueKeyId (base name: "unique_key_id")', function() {
        // TODO: update the code to test the property uniqueKeyId
        expect(instance).to.have.property('uniqueKeyId');
        // expect(instance.uniqueKeyId).to.be(expectedValueLiteral);
      });

      it('should have the property cityCode (base name: "city_code")', function() {
        // TODO: update the code to test the property cityCode
        expect(instance).to.have.property('cityCode');
        // expect(instance.cityCode).to.be(expectedValueLiteral);
      });

      it('should have the property keyPair (base name: "key_pair")', function() {
        // TODO: update the code to test the property keyPair
        expect(instance).to.have.property('keyPair');
        // expect(instance.keyPair).to.be(expectedValueLiteral);
      });

    });
  });

}));
