/*
 * ONDC Registry 
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OndcRegistry_);
  }
}(this, function(expect, OndcRegistry_) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VlookupBody', function() {
      beforeEach(function() {
        instance = new OndcRegistry_.VlookupBody();
      });

      it('should create an instance of VlookupBody', function() {
        // TODO: update the code to test VlookupBody
        expect(instance).to.be.a(OndcRegistry_.VlookupBody);
      });

      it('should have the property senderSubscriberId (base name: "sender_subscriber_id")', function() {
        // TODO: update the code to test the property senderSubscriberId
        expect(instance).to.have.property('senderSubscriberId');
        // expect(instance.senderSubscriberId).to.be(expectedValueLiteral);
      });

      it('should have the property requestId (base name: "request_id")', function() {
        // TODO: update the code to test the property requestId
        expect(instance).to.have.property('requestId');
        // expect(instance.requestId).to.be(expectedValueLiteral);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

      it('should have the property searchParameters (base name: "search_parameters")', function() {
        // TODO: update the code to test the property searchParameters
        expect(instance).to.have.property('searchParameters');
        // expect(instance.searchParameters).to.be(expectedValueLiteral);
      });

      it('should have the property signature (base name: "signature")', function() {
        // TODO: update the code to test the property signature
        expect(instance).to.have.property('signature');
        // expect(instance.signature).to.be(expectedValueLiteral);
      });

    });
  });

}));
