/*
 * ONDC Protocol API for retail (grocery, f&b)
 * ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.13
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CityCode} from './CityCode';

/**
 * The City model module.
 * @module model/City
 * @version 1.0.13
 */
export class City {
  /**
   * Constructs a new <code>City</code>.
   * Describes a city
   * @alias module:model/City
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>City</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/City} obj Optional instance to populate.
   * @return {module:model/City} The populated <code>City</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new City();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = CityCode.constructFromObject(data['code']);
    }
    return obj;
  }
}

/**
 * Name of the city
 * @member {String} name
 */
City.prototype.name = undefined;

/**
 * @member {module:model/CityCode} code
 */
City.prototype.code = undefined;

