/*
 * ONDC Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.45
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Gps} from './Gps';
import {Scalar} from './Scalar';

/**
 * The Circle model module.
 * @module model/Circle
 * @version 1.0.0
 */
export class Circle {
  /**
   * Constructs a new <code>Circle</code>.
   * Describes a circular area on the map
   * @alias module:model/Circle
   * @class
   * @param gps {module:model/Gps} 
   * @param radius {module:model/Scalar} 
   */
  constructor(gps, radius) {
    this.gps = gps;
    this.radius = radius;
  }

  /**
   * Constructs a <code>Circle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Circle} obj Optional instance to populate.
   * @return {module:model/Circle} The populated <code>Circle</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Circle();
      if (data.hasOwnProperty('gps'))
        obj.gps = Gps.constructFromObject(data['gps']);
      if (data.hasOwnProperty('radius'))
        obj.radius = Scalar.constructFromObject(data['radius']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Gps} gps
 */
Circle.prototype.gps = undefined;

/**
 * @member {module:model/Scalar} radius
 */
Circle.prototype.radius = undefined;

