/*
 * ONDC Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.45
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ScalarRange model module.
 * @module model/ScalarRange
 * @version 1.0.0
 */
export class ScalarRange {
  /**
   * Constructs a new <code>ScalarRange</code>.
   * @alias module:model/ScalarRange
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ScalarRange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScalarRange} obj Optional instance to populate.
   * @return {module:model/ScalarRange} The populated <code>ScalarRange</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ScalarRange();
      if (data.hasOwnProperty('min'))
        obj.min = ApiClient.convertToType(data['min'], 'Number');
      if (data.hasOwnProperty('max'))
        obj.max = ApiClient.convertToType(data['max'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} min
 */
ScalarRange.prototype.min = undefined;

/**
 * @member {Number} max
 */
ScalarRange.prototype.max = undefined;

