/*
 * ONDC Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.45
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Vehicle model module.
 * @module model/Vehicle
 * @version 1.0.0
 */
export class Vehicle {
  /**
   * Constructs a new <code>Vehicle</code>.
   * Describes the properties of a vehicle used in a mobility service
   * @alias module:model/Vehicle
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Vehicle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vehicle} obj Optional instance to populate.
   * @return {module:model/Vehicle} The populated <code>Vehicle</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Vehicle();
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('capacity'))
        obj.capacity = ApiClient.convertToType(data['capacity'], 'Number');
      if (data.hasOwnProperty('make'))
        obj.make = ApiClient.convertToType(data['make'], 'String');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'String');
      if (data.hasOwnProperty('variant'))
        obj.variant = ApiClient.convertToType(data['variant'], 'String');
      if (data.hasOwnProperty('color'))
        obj.color = ApiClient.convertToType(data['color'], 'String');
      if (data.hasOwnProperty('energy_type'))
        obj.energyType = ApiClient.convertToType(data['energy_type'], 'String');
      if (data.hasOwnProperty('registration'))
        obj.registration = ApiClient.convertToType(data['registration'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} category
 */
Vehicle.prototype.category = undefined;

/**
 * @member {Number} capacity
 */
Vehicle.prototype.capacity = undefined;

/**
 * @member {String} make
 */
Vehicle.prototype.make = undefined;

/**
 * @member {String} model
 */
Vehicle.prototype.model = undefined;

/**
 * @member {String} size
 */
Vehicle.prototype.size = undefined;

/**
 * @member {String} variant
 */
Vehicle.prototype.variant = undefined;

/**
 * @member {String} color
 */
Vehicle.prototype.color = undefined;

/**
 * @member {String} energyType
 */
Vehicle.prototype.energyType = undefined;

/**
 * @member {String} registration
 */
Vehicle.prototype.registration = undefined;

