/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OndcProtocolCoreApi);
  }
}(this, function(expect, OndcProtocolCoreApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Quotation', function() {
      beforeEach(function() {
        instance = new OndcProtocolCoreApi.Quotation();
      });

      it('should create an instance of Quotation', function() {
        // TODO: update the code to test Quotation
        expect(instance).to.be.a(OndcProtocolCoreApi.Quotation);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property breakup (base name: "breakup")', function() {
        // TODO: update the code to test the property breakup
        expect(instance).to.have.property('breakup');
        // expect(instance.breakup).to.be(expectedValueLiteral);
      });

      it('should have the property ttl (base name: "ttl")', function() {
        // TODO: update the code to test the property ttl
        expect(instance).to.have.property('ttl');
        // expect(instance.ttl).to.be(expectedValueLiteral);
      });

    });
  });

}));
