/*
 * ONDC Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.45
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OndcGateway);
  }
}(this, function(expect, OndcGateway) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CategoryId', function() {
      beforeEach(function() {
        instance = OndcGateway.CategoryId;
      });

      it('should create an instance of CategoryId', function() {
        // TODO: update the code to test CategoryId
        expect(instance).to.be.a('object');
      });

      it('should have the property grocery', function() {
        expect(instance).to.have.property('grocery');
        expect(instance.grocery).to.be("Grocery");
      });

      it('should have the property packagedCommodities', function() {
        expect(instance).to.have.property('packagedCommodities');
        expect(instance.packagedCommodities).to.be("Packaged Commodities");
      });

      it('should have the property packagedFoods', function() {
        expect(instance).to.have.property('packagedFoods');
        expect(instance.packagedFoods).to.be("Packaged Foods");
      });

      it('should have the property fruitsAndVegetables', function() {
        expect(instance).to.have.property('fruitsAndVegetables');
        expect(instance.fruitsAndVegetables).to.be("Fruits and Vegetables");
      });

      it('should have the property FB', function() {
        expect(instance).to.have.property('FB');
        expect(instance.FB).to.be("F&B");
      });

      it('should have the property homeDecor', function() {
        expect(instance).to.have.property('homeDecor');
        expect(instance.homeDecor).to.be("Home & Decor");
      });

    });
  });

}));
