/*
 * ONDC Protocol API for logistics
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Context} from './Context';
import {SelectMessage} from './SelectMessage';

/**
 * The ConfirmBody model module.
 * @module model/ConfirmBody
 * @version 1.0.9
 */
export class ConfirmBody {
  /**
   * Constructs a new <code>ConfirmBody</code>.
   * @alias module:model/ConfirmBody
   * @class
   * @param context {module:model/Context} 
   * @param message {module:model/SelectMessage} 
   */
  constructor(context, message) {
    this.context = context;
    this.message = message;
  }

  /**
   * Constructs a <code>ConfirmBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConfirmBody} obj Optional instance to populate.
   * @return {module:model/ConfirmBody} The populated <code>ConfirmBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ConfirmBody();
      if (data.hasOwnProperty('context'))
        obj.context = Context.constructFromObject(data['context']);
      if (data.hasOwnProperty('message'))
        obj.message = SelectMessage.constructFromObject(data['message']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Context} context
 */
ConfirmBody.prototype.context = undefined;

/**
 * @member {module:model/SelectMessage} message
 */
ConfirmBody.prototype.message = undefined;

