/*
 * ONDC Protocol API for logistics
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ItemQuantitypropertiesselected} from './ItemQuantitypropertiesselected';
import {Itempropertiesid} from './Itempropertiesid';

/**
 * The OnInitMessageOrderItems model module.
 * @module model/OnInitMessageOrderItems
 * @version 1.0.9
 */
export class OnInitMessageOrderItems {
  /**
   * Constructs a new <code>OnInitMessageOrderItems</code>.
   * @alias module:model/OnInitMessageOrderItems
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OnInitMessageOrderItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnInitMessageOrderItems} obj Optional instance to populate.
   * @return {module:model/OnInitMessageOrderItems} The populated <code>OnInitMessageOrderItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OnInitMessageOrderItems();
      if (data.hasOwnProperty('id'))
        obj.id = Itempropertiesid.constructFromObject(data['id']);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ItemQuantitypropertiesselected.constructFromObject(data['quantity']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Itempropertiesid} id
 */
OnInitMessageOrderItems.prototype.id = undefined;

/**
 * @member {module:model/ItemQuantitypropertiesselected} quantity
 */
OnInitMessageOrderItems.prototype.quantity = undefined;

