/*
 * ONDC Protocol API for logistics
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OrderProviderLocations} from './OrderProviderLocations';
import {Providerpropertiesid} from './Providerpropertiesid';

/**
 * The OrderProvider model module.
 * @module model/OrderProvider
 * @version 1.0.9
 */
export class OrderProvider {
  /**
   * Constructs a new <code>OrderProvider</code>.
   * @alias module:model/OrderProvider
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderProvider</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderProvider} obj Optional instance to populate.
   * @return {module:model/OrderProvider} The populated <code>OrderProvider</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderProvider();
      if (data.hasOwnProperty('id'))
        obj.id = Providerpropertiesid.constructFromObject(data['id']);
      if (data.hasOwnProperty('locations'))
        obj.locations = ApiClient.convertToType(data['locations'], [OrderProviderLocations]);
    }
    return obj;
  }
}

/**
 * @member {module:model/Providerpropertiesid} id
 */
OrderProvider.prototype.id = undefined;

/**
 * @member {Array.<module:model/OrderProviderLocations>} locations
 */
OrderProvider.prototype.locations = undefined;

