/*
 * ONDC Protocol API for logistics
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Address} from './Address';
import {Descriptorpropertiesname} from './Descriptorpropertiesname';
import {Providerpropertiesid} from './Providerpropertiesid';

/**
 * The OrderOndcorglinkedOrderProvider model module.
 * @module model/OrderOndcorglinkedOrderProvider
 * @version 1.0.9
 */
export class OrderOndcorglinkedOrderProvider {
  /**
   * Constructs a new <code>OrderOndcorglinkedOrderProvider</code>.
   * @alias module:model/OrderOndcorglinkedOrderProvider
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderOndcorglinkedOrderProvider</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderOndcorglinkedOrderProvider} obj Optional instance to populate.
   * @return {module:model/OrderOndcorglinkedOrderProvider} The populated <code>OrderOndcorglinkedOrderProvider</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderOndcorglinkedOrderProvider();
      if (data.hasOwnProperty('id'))
        obj.id = Providerpropertiesid.constructFromObject(data['id']);
      if (data.hasOwnProperty('name'))
        obj.name = Descriptorpropertiesname.constructFromObject(data['name']);
      if (data.hasOwnProperty('address'))
        obj.address = Address.constructFromObject(data['address']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Providerpropertiesid} id
 */
OrderOndcorglinkedOrderProvider.prototype.id = undefined;

/**
 * @member {module:model/Descriptorpropertiesname} name
 */
OrderOndcorglinkedOrderProvider.prototype.name = undefined;

/**
 * @member {module:model/Address} address
 */
OrderOndcorglinkedOrderProvider.prototype.address = undefined;

