/*
 * ONDC Protocol API for logistics
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DecimalValue} from './DecimalValue';
import {Dimensions} from './Dimensions';
import {Orderpropertiesid} from './Orderpropertiesid';
import {Price} from './Price';
import {Scalar} from './Scalar';

/**
 * The OrderOndcorglinkedOrderOrder model module.
 * @module model/OrderOndcorglinkedOrderOrder
 * @version 1.0.9
 */
export class OrderOndcorglinkedOrderOrder {
  /**
   * Constructs a new <code>OrderOndcorglinkedOrderOrder</code>.
   * use same units for weight and dimensions as defined for Intent
   * @alias module:model/OrderOndcorglinkedOrderOrder
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderOndcorglinkedOrderOrder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderOndcorglinkedOrderOrder} obj Optional instance to populate.
   * @return {module:model/OrderOndcorglinkedOrderOrder} The populated <code>OrderOndcorglinkedOrderOrder</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderOndcorglinkedOrderOrder();
      if (data.hasOwnProperty('id'))
        obj.id = Orderpropertiesid.constructFromObject(data['id']);
      if (data.hasOwnProperty('weight'))
        obj.weight = Scalar.constructFromObject(data['weight']);
      if (data.hasOwnProperty('dimensions'))
        obj.dimensions = Dimensions.constructFromObject(data['dimensions']);
      if (data.hasOwnProperty('declared_value'))
        obj.declaredValue = Price.constructFromObject(data['declared_value']);
      if (data.hasOwnProperty('taxable_value'))
        obj.taxableValue = Price.constructFromObject(data['taxable_value']);
      if (data.hasOwnProperty('hsn_code'))
        obj.hsnCode = ApiClient.convertToType(data['hsn_code'], 'String');
      if (data.hasOwnProperty('sgst_amount'))
        obj.sgstAmount = DecimalValue.constructFromObject(data['sgst_amount']);
      if (data.hasOwnProperty('cgst_amount'))
        obj.cgstAmount = DecimalValue.constructFromObject(data['cgst_amount']);
      if (data.hasOwnProperty('igst_amount'))
        obj.igstAmount = DecimalValue.constructFromObject(data['igst_amount']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Orderpropertiesid} id
 */
OrderOndcorglinkedOrderOrder.prototype.id = undefined;

/**
 * @member {module:model/Scalar} weight
 */
OrderOndcorglinkedOrderOrder.prototype.weight = undefined;

/**
 * @member {module:model/Dimensions} dimensions
 */
OrderOndcorglinkedOrderOrder.prototype.dimensions = undefined;

/**
 * @member {module:model/Price} declaredValue
 */
OrderOndcorglinkedOrderOrder.prototype.declaredValue = undefined;

/**
 * @member {module:model/Price} taxableValue
 */
OrderOndcorglinkedOrderOrder.prototype.taxableValue = undefined;

/**
 * @member {String} hsnCode
 */
OrderOndcorglinkedOrderOrder.prototype.hsnCode = undefined;

/**
 * @member {module:model/DecimalValue} sgstAmount
 */
OrderOndcorglinkedOrderOrder.prototype.sgstAmount = undefined;

/**
 * @member {module:model/DecimalValue} cgstAmount
 */
OrderOndcorglinkedOrderOrder.prototype.cgstAmount = undefined;

/**
 * @member {module:model/DecimalValue} igstAmount
 */
OrderOndcorglinkedOrderOrder.prototype.igstAmount = undefined;

