/*
 * ONDC Protocol API for logistics
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Orderpropertiesid} from './Orderpropertiesid';

/**
 * The StatusMessage model module.
 * @module model/StatusMessage
 * @version 1.0.9
 */
export class StatusMessage {
  /**
   * Constructs a new <code>StatusMessage</code>.
   * @alias module:model/StatusMessage
   * @class
   * @param orderId {module:model/Orderpropertiesid} 
   */
  constructor(orderId) {
    this.orderId = orderId;
  }

  /**
   * Constructs a <code>StatusMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatusMessage} obj Optional instance to populate.
   * @return {module:model/StatusMessage} The populated <code>StatusMessage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StatusMessage();
      if (data.hasOwnProperty('order_id'))
        obj.orderId = Orderpropertiesid.constructFromObject(data['order_id']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Orderpropertiesid} orderId
 */
StatusMessage.prototype.orderId = undefined;

