/*
 * ONDC Protocol API for retail (grocery, f&b)
 * ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Optionpropertiesid} from './Optionpropertiesid';

/**
 * The CancellationSelectedReason model module.
 * @module model/CancellationSelectedReason
 * @version 1.0.29
 */
export class CancellationSelectedReason {
  /**
   * Constructs a new <code>CancellationSelectedReason</code>.
   * @alias module:model/CancellationSelectedReason
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CancellationSelectedReason</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CancellationSelectedReason} obj Optional instance to populate.
   * @return {module:model/CancellationSelectedReason} The populated <code>CancellationSelectedReason</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CancellationSelectedReason();
      if (data.hasOwnProperty('id'))
        obj.id = Optionpropertiesid.constructFromObject(data['id']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Optionpropertiesid} id
 */
CancellationSelectedReason.prototype.id = undefined;

