/*
 * ONDC Protocol API for retail (grocery, f&b)
 * ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddOnpropertiesid} from './AddOnpropertiesid';

/**
 * The OrderAddOns model module.
 * @module model/OrderAddOns
 * @version 1.0.29
 */
export class OrderAddOns {
  /**
   * Constructs a new <code>OrderAddOns</code>.
   * @alias module:model/OrderAddOns
   * @class
   * @param id {module:model/AddOnpropertiesid} 
   */
  constructor(id) {
    this.id = id;
  }

  /**
   * Constructs a <code>OrderAddOns</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderAddOns} obj Optional instance to populate.
   * @return {module:model/OrderAddOns} The populated <code>OrderAddOns</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderAddOns();
      if (data.hasOwnProperty('id'))
        obj.id = AddOnpropertiesid.constructFromObject(data['id']);
    }
    return obj;
  }
}

/**
 * @member {module:model/AddOnpropertiesid} id
 */
OrderAddOns.prototype.id = undefined;

