/*
 * ONDC Registry 
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The City model module.
 * @module model/City
 * @version 2.0.5
 */
export class City {
  /**
   * Constructs a new <code>City</code>.
   * Codification of city code will be using the std code of the city e.g. for Bengaluru, city code is &#x27;std:080&#x27;
   * @alias module:model/City
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>City</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/City} obj Optional instance to populate.
   * @return {module:model/City} The populated <code>City</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new City();
    }
    return obj;
  }
}
