/*
 * ONDC Registry 
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The VlookupKeyPair model module.
 * @module model/VlookupKeyPair
 * @version 2.0.5
 */
export class VlookupKeyPair {
  /**
   * Constructs a new <code>VlookupKeyPair</code>.
   * @alias module:model/VlookupKeyPair
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>VlookupKeyPair</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VlookupKeyPair} obj Optional instance to populate.
   * @return {module:model/VlookupKeyPair} The populated <code>VlookupKeyPair</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VlookupKeyPair();
      if (data.hasOwnProperty('signing_public_key'))
        obj.signingPublicKey = ApiClient.convertToType(data['signing_public_key'], 'String');
      if (data.hasOwnProperty('encr_public_key'))
        obj.encrPublicKey = ApiClient.convertToType(data['encr_public_key'], 'String');
      if (data.hasOwnProperty('valid_from'))
        obj.validFrom = ApiClient.convertToType(data['valid_from'], 'String');
      if (data.hasOwnProperty('valid_until'))
        obj.validUntil = ApiClient.convertToType(data['valid_until'], 'String');
    }
    return obj;
  }
}

/**
 * Signing Public Key
 * @member {String} signingPublicKey
 */
VlookupKeyPair.prototype.signingPublicKey = undefined;

/**
 * Encryption Public Key
 * @member {String} encrPublicKey
 */
VlookupKeyPair.prototype.encrPublicKey = undefined;

/**
 * Keys valid from
 * @member {String} validFrom
 */
VlookupKeyPair.prototype.validFrom = undefined;

/**
 * Keys valid until
 * @member {String} validUntil
 */
VlookupKeyPair.prototype.validUntil = undefined;

