/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Orderhistory} from '../model/Orderhistory';

/**
* OrderHistory service.
* @module api/OrderHistoryApi
* @version 1.0
*/
export class OrderHistoryApi {

    /**
    * Constructs a new OrderHistoryApi. 
    * @alias module:api/OrderHistoryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the orderhistory operation.
     * @callback moduleapi/OrderHistoryApi~orderhistoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Orderhistory{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * order history
     * @param {Number} pageNumber Number - from 1 to ....
     * @param {Number} limit 
     * @param {module:model/String} contentType 
     * @param {module:api/OrderHistoryApi~orderhistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    orderhistory(pageNumber, limit, contentType, callback) {
      
      let postBody = null;
      // verify the required parameter 'pageNumber' is set
      if (pageNumber === undefined || pageNumber === null) {
        throw new Error("Missing the required parameter 'pageNumber' when calling orderhistory");
      }
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling orderhistory");
      }
      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling orderhistory");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'pageNumber': pageNumber,'limit': limit
      };
      let headerParams = {
        'Content-Type': contentType
      };
      let formParams = {
        
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Orderhistory;

      return this.apiClient.callApi(
        '/v1/orders', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}