/*
 * ONDC Protocol API for retail (grocery, f&b)
 * ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.13
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OndcProtocolApiForRetailGroceryFb);
  }
}(this, function(expect, OndcProtocolApiForRetailGroceryFb) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FeedbackUrlParams', function() {
      beforeEach(function() {
        instance = new OndcProtocolApiForRetailGroceryFb.FeedbackUrlParams();
      });

      it('should create an instance of FeedbackUrlParams', function() {
        // TODO: update the code to test FeedbackUrlParams
        expect(instance).to.be.a(OndcProtocolApiForRetailGroceryFb.FeedbackUrlParams);
      });

      it('should have the property feedbackId (base name: "feedback_id")', function() {
        // TODO: update the code to test the property feedbackId
        expect(instance).to.have.property('feedbackId');
        // expect(instance.feedbackId).to.be(expectedValueLiteral);
      });

    });
  });

}));
