/*
 * ONDC Protocol API for retail (grocery, f&b)
 * ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.13
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Descriptor} from './Descriptor';
import {Price} from './Price';

/**
 * The AddOn model module.
 * @module model/AddOn
 * @version 1.0.13
 */
export class AddOn {
  /**
   * Constructs a new <code>AddOn</code>.
   * Describes an add-on
   * @alias module:model/AddOn
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AddOn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddOn} obj Optional instance to populate.
   * @return {module:model/AddOn} The populated <code>AddOn</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddOn();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('descriptor'))
        obj.descriptor = Descriptor.constructFromObject(data['descriptor']);
      if (data.hasOwnProperty('price'))
        obj.price = Price.constructFromObject(data['price']);
    }
    return obj;
  }
}

/**
 * ID of the add-on. This follows the syntax {item.id}/add-on/{add-on unique id} for item specific add-on OR 
 * @member {String} id
 */
AddOn.prototype.id = undefined;

/**
 * @member {module:model/Descriptor} descriptor
 */
AddOn.prototype.descriptor = undefined;

/**
 * @member {module:model/Price} price
 */
AddOn.prototype.price = undefined;

