/*
 * ONDC Protocol API for retail (grocery, f&b)
 * ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.13
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Locationpropertiesid} from './Locationpropertiesid';

/**
 * The OnInitMessageOrderProviderLocation model module.
 * @module model/OnInitMessageOrderProviderLocation
 * @version 1.0.13
 */
export class OnInitMessageOrderProviderLocation {
  /**
   * Constructs a new <code>OnInitMessageOrderProviderLocation</code>.
   * @alias module:model/OnInitMessageOrderProviderLocation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OnInitMessageOrderProviderLocation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnInitMessageOrderProviderLocation} obj Optional instance to populate.
   * @return {module:model/OnInitMessageOrderProviderLocation} The populated <code>OnInitMessageOrderProviderLocation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OnInitMessageOrderProviderLocation();
      if (data.hasOwnProperty('id'))
        obj.id = Locationpropertiesid.constructFromObject(data['id']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Locationpropertiesid} id
 */
OnInitMessageOrderProviderLocation.prototype.id = undefined;

