/*
 * ONDC Registry 
 * ONDC Participant Management API
 *
 * OpenAPI spec version: 2.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OndcRegistry_);
  }
}(this, function(expect, OndcRegistry_) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OndcRegistry_.ONDCNetworkParticipantOnboardingApi();
  });

  describe('(package)', function() {
    describe('ONDCNetworkParticipantOnboardingApi', function() {
      describe('lookupPost', function() {
        it('should call lookupPost successfully', function(done) {
          // TODO: uncomment, update parameter values for lookupPost call and complete the assertions
          /*
          var opts = {};

          instance.lookupPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(OndcRegistry_.InlineResponse2002);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subscribePost', function() {
        it('should call subscribePost successfully', function(done) {
          // TODO: uncomment, update parameter values for subscribePost call and complete the assertions
          /*
          var opts = {};

          instance.subscribePost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OndcRegistry_.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subscriberUrlOnSubscribePost', function() {
        it('should call subscriberUrlOnSubscribePost successfully', function(done) {
          // TODO: uncomment, update parameter values for subscriberUrlOnSubscribePost call and complete the assertions
          /*
          var opts = {};

          instance.subscriberUrlOnSubscribePost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OndcRegistry_.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
