/*
 * ONDC Protocol API for retail (grocery, f&b)
 * ONDC Protocol API specification, which includes statutory requirements for packaged commodities and pre-packaged food This is an adaptation of Beckn Core version 0.9.3
 *
 * OpenAPI spec version: 1.0.13
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Context} from './Context';
import {Error} from './Error';
import {SelectMessage} from './SelectMessage';

/**
 * The OnCancelBody model module.
 * @module model/OnCancelBody
 * @version 1.0.13
 */
export class OnCancelBody {
  /**
   * Constructs a new <code>OnCancelBody</code>.
   * @alias module:model/OnCancelBody
   * @class
   * @param context {module:model/Context} 
   */
  constructor(context) {
    this.context = context;
  }

  /**
   * Constructs a <code>OnCancelBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnCancelBody} obj Optional instance to populate.
   * @return {module:model/OnCancelBody} The populated <code>OnCancelBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OnCancelBody();
      if (data.hasOwnProperty('context'))
        obj.context = Context.constructFromObject(data['context']);
      if (data.hasOwnProperty('message'))
        obj.message = SelectMessage.constructFromObject(data['message']);
      if (data.hasOwnProperty('error'))
        obj.error = Error.constructFromObject(data['error']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Context} context
 */
OnCancelBody.prototype.context = undefined;

/**
 * @member {module:model/SelectMessage} message
 */
OnCancelBody.prototype.message = undefined;

/**
 * @member {module:model/Error} error
 */
OnCancelBody.prototype.error = undefined;

