/*
 * ONDC Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.45
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Ack} from './model/Ack';
import {Address} from './model/Address';
import {Agent} from './model/Agent';
import {AllOfProviderLocationsItems} from './model/AllOfProviderLocationsItems';
import {Authorization} from './model/Authorization';
import {Catalog} from './model/Catalog';
import {Category} from './model/Category';
import {CategoryId} from './model/CategoryId';
import {Circle} from './model/Circle';
import {City} from './model/City';
import {CityCode} from './model/CityCode';
import {Contact} from './model/Contact';
import {Context} from './model/Context';
import {Country} from './model/Country';
import {CountryCode} from './model/CountryCode';
import {Currency} from './model/Currency';
import {DecimalValue} from './model/DecimalValue';
import {Descriptor} from './model/Descriptor';
import {Domain} from './model/Domain';
import {Duration} from './model/Duration';
import {Error} from './model/Error';
import {Fulfillment} from './model/Fulfillment';
import {FulfillmentCustomer} from './model/FulfillmentCustomer';
import {FulfillmentEnd} from './model/FulfillmentEnd';
import {FulfillmentId} from './model/FulfillmentId';
import {FulfillmentStart} from './model/FulfillmentStart';
import {Gps} from './model/Gps';
import {Image} from './model/Image';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse200Message} from './model/InlineResponse200Message';
import {Intent} from './model/Intent';
import {Item} from './model/Item';
import {ItemId} from './model/ItemId';
import {ItemOndcorgstatutoryReqsPackagedCommodities} from './model/ItemOndcorgstatutoryReqsPackagedCommodities';
import {ItemOndcorgstatutoryReqsPrepackagedFood} from './model/ItemOndcorgstatutoryReqsPrepackagedFood';
import {Location} from './model/Location';
import {LocationId} from './model/LocationId';
import {Name} from './model/Name';
import {Offer} from './model/Offer';
import {OnSearchBody} from './model/OnSearchBody';
import {OnSearchMessage} from './model/OnSearchMessage';
import {Payment} from './model/Payment';
import {PaymentOndcorgsettlementDetails} from './model/PaymentOndcorgsettlementDetails';
import {PaymentParams} from './model/PaymentParams';
import {Person} from './model/Person';
import {Price} from './model/Price';
import {Provider} from './model/Provider';
import {ProviderId} from './model/ProviderId';
import {Rateable} from './model/Rateable';
import {Scalar} from './model/Scalar';
import {ScalarRange} from './model/ScalarRange';
import {Schedule} from './model/Schedule';
import {SearchBody} from './model/SearchBody';
import {SearchMessage} from './model/SearchMessage';
import {State} from './model/State';
import {Tags} from './model/Tags';
import {Time} from './model/Time';
import {TimeRange} from './model/TimeRange';
import {Vehicle} from './model/Vehicle';
import {ONDCGatewayApi} from './api/ONDCGatewayApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OndcGateway = require('index'); // See note below*.
* var xxxSvc = new OndcGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OndcGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OndcGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OndcGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export default {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Ack model constructor.
     * @property {module:model/Ack}
     */
    Ack,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The Agent model constructor.
     * @property {module:model/Agent}
     */
    Agent,

    /**
     * The AllOfProviderLocationsItems model constructor.
     * @property {module:model/AllOfProviderLocationsItems}
     */
    AllOfProviderLocationsItems,

    /**
     * The Authorization model constructor.
     * @property {module:model/Authorization}
     */
    Authorization,

    /**
     * The Catalog model constructor.
     * @property {module:model/Catalog}
     */
    Catalog,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The CategoryId model constructor.
     * @property {module:model/CategoryId}
     */
    CategoryId,

    /**
     * The Circle model constructor.
     * @property {module:model/Circle}
     */
    Circle,

    /**
     * The City model constructor.
     * @property {module:model/City}
     */
    City,

    /**
     * The CityCode model constructor.
     * @property {module:model/CityCode}
     */
    CityCode,

    /**
     * The Contact model constructor.
     * @property {module:model/Contact}
     */
    Contact,

    /**
     * The Context model constructor.
     * @property {module:model/Context}
     */
    Context,

    /**
     * The Country model constructor.
     * @property {module:model/Country}
     */
    Country,

    /**
     * The CountryCode model constructor.
     * @property {module:model/CountryCode}
     */
    CountryCode,

    /**
     * The Currency model constructor.
     * @property {module:model/Currency}
     */
    Currency,

    /**
     * The DecimalValue model constructor.
     * @property {module:model/DecimalValue}
     */
    DecimalValue,

    /**
     * The Descriptor model constructor.
     * @property {module:model/Descriptor}
     */
    Descriptor,

    /**
     * The Domain model constructor.
     * @property {module:model/Domain}
     */
    Domain,

    /**
     * The Duration model constructor.
     * @property {module:model/Duration}
     */
    Duration,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Fulfillment model constructor.
     * @property {module:model/Fulfillment}
     */
    Fulfillment,

    /**
     * The FulfillmentCustomer model constructor.
     * @property {module:model/FulfillmentCustomer}
     */
    FulfillmentCustomer,

    /**
     * The FulfillmentEnd model constructor.
     * @property {module:model/FulfillmentEnd}
     */
    FulfillmentEnd,

    /**
     * The FulfillmentId model constructor.
     * @property {module:model/FulfillmentId}
     */
    FulfillmentId,

    /**
     * The FulfillmentStart model constructor.
     * @property {module:model/FulfillmentStart}
     */
    FulfillmentStart,

    /**
     * The Gps model constructor.
     * @property {module:model/Gps}
     */
    Gps,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse200Message model constructor.
     * @property {module:model/InlineResponse200Message}
     */
    InlineResponse200Message,

    /**
     * The Intent model constructor.
     * @property {module:model/Intent}
     */
    Intent,

    /**
     * The Item model constructor.
     * @property {module:model/Item}
     */
    Item,

    /**
     * The ItemId model constructor.
     * @property {module:model/ItemId}
     */
    ItemId,

    /**
     * The ItemOndcorgstatutoryReqsPackagedCommodities model constructor.
     * @property {module:model/ItemOndcorgstatutoryReqsPackagedCommodities}
     */
    ItemOndcorgstatutoryReqsPackagedCommodities,

    /**
     * The ItemOndcorgstatutoryReqsPrepackagedFood model constructor.
     * @property {module:model/ItemOndcorgstatutoryReqsPrepackagedFood}
     */
    ItemOndcorgstatutoryReqsPrepackagedFood,

    /**
     * The Location model constructor.
     * @property {module:model/Location}
     */
    Location,

    /**
     * The LocationId model constructor.
     * @property {module:model/LocationId}
     */
    LocationId,

    /**
     * The Name model constructor.
     * @property {module:model/Name}
     */
    Name,

    /**
     * The Offer model constructor.
     * @property {module:model/Offer}
     */
    Offer,

    /**
     * The OnSearchBody model constructor.
     * @property {module:model/OnSearchBody}
     */
    OnSearchBody,

    /**
     * The OnSearchMessage model constructor.
     * @property {module:model/OnSearchMessage}
     */
    OnSearchMessage,

    /**
     * The Payment model constructor.
     * @property {module:model/Payment}
     */
    Payment,

    /**
     * The PaymentOndcorgsettlementDetails model constructor.
     * @property {module:model/PaymentOndcorgsettlementDetails}
     */
    PaymentOndcorgsettlementDetails,

    /**
     * The PaymentParams model constructor.
     * @property {module:model/PaymentParams}
     */
    PaymentParams,

    /**
     * The Person model constructor.
     * @property {module:model/Person}
     */
    Person,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The Provider model constructor.
     * @property {module:model/Provider}
     */
    Provider,

    /**
     * The ProviderId model constructor.
     * @property {module:model/ProviderId}
     */
    ProviderId,

    /**
     * The Rateable model constructor.
     * @property {module:model/Rateable}
     */
    Rateable,

    /**
     * The Scalar model constructor.
     * @property {module:model/Scalar}
     */
    Scalar,

    /**
     * The ScalarRange model constructor.
     * @property {module:model/ScalarRange}
     */
    ScalarRange,

    /**
     * The Schedule model constructor.
     * @property {module:model/Schedule}
     */
    Schedule,

    /**
     * The SearchBody model constructor.
     * @property {module:model/SearchBody}
     */
    SearchBody,

    /**
     * The SearchMessage model constructor.
     * @property {module:model/SearchMessage}
     */
    SearchMessage,

    /**
     * The State model constructor.
     * @property {module:model/State}
     */
    State,

    /**
     * The Tags model constructor.
     * @property {module:model/Tags}
     */
    Tags,

    /**
     * The Time model constructor.
     * @property {module:model/Time}
     */
    Time,

    /**
     * The TimeRange model constructor.
     * @property {module:model/TimeRange}
     */
    TimeRange,

    /**
     * The Vehicle model constructor.
     * @property {module:model/Vehicle}
     */
    Vehicle,

    /**
    * The ONDCGatewayApi service constructor.
    * @property {module:api/ONDCGatewayApi}
    */
    ONDCGatewayApi
};
