/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Address2 model module.
 * @module model/Address2
 * @version 1.0
 */
export class Address2 {
  /**
   * Constructs a new <code>Address2</code>.
   * @alias module:model/Address2
   * @class
   * @param door {String} 
   * @param country {String} 
   * @param street {String} 
   * @param areaCode {String} 
   * @param name {String} 
   * @param locality {String} 
   * @param state {String} 
   * @param building {String} 
   */
  constructor(door, country, street, areaCode, name, locality, state, building) {
    this.door = door;
    this.country = country;
    this.street = street;
    this.areaCode = areaCode;
    this.name = name;
    this.locality = locality;
    this.state = state;
    this.building = building;
  }

  /**
   * Constructs a <code>Address2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Address2} obj Optional instance to populate.
   * @return {module:model/Address2} The populated <code>Address2</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Address2();
      if (data.hasOwnProperty('door'))
        obj.door = ApiClient.convertToType(data['door'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('street'))
        obj.street = ApiClient.convertToType(data['street'], 'String');
      if (data.hasOwnProperty('area_code'))
        obj.areaCode = ApiClient.convertToType(data['area_code'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('locality'))
        obj.locality = ApiClient.convertToType(data['locality'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('building'))
        obj.building = ApiClient.convertToType(data['building'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} door
 */
Address2.prototype.door = undefined;

/**
 * @member {String} country
 */
Address2.prototype.country = undefined;

/**
 * @member {String} street
 */
Address2.prototype.street = undefined;

/**
 * @member {String} areaCode
 */
Address2.prototype.areaCode = undefined;

/**
 * @member {String} name
 */
Address2.prototype.name = undefined;

/**
 * @member {String} locality
 */
Address2.prototype.locality = undefined;

/**
 * @member {String} state
 */
Address2.prototype.state = undefined;

/**
 * @member {String} building
 */
Address2.prototype.building = undefined;

