/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Price1} from './Price1';

/**
 * The Breakup model module.
 * @module model/Breakup
 * @version 1.0
 */
export class Breakup {
  /**
   * Constructs a new <code>Breakup</code>.
   * @alias module:model/Breakup
   * @class
   * @param title {String} 
   * @param price {module:model/Price1} 
   */
  constructor(title, price) {
    this.title = title;
    this.price = price;
  }

  /**
   * Constructs a <code>Breakup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Breakup} obj Optional instance to populate.
   * @return {module:model/Breakup} The populated <code>Breakup</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Breakup();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = Price1.constructFromObject(data['price']);
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
Breakup.prototype.title = undefined;

/**
 * @member {module:model/Price1} price
 */
Breakup.prototype.price = undefined;

