/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Descriptor3 model module.
 * @module model/Descriptor3
 * @version 1.0
 */
export class Descriptor3 {
  /**
   * Constructs a new <code>Descriptor3</code>.
   * @alias module:model/Descriptor3
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Descriptor3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Descriptor3} obj Optional instance to populate.
   * @return {module:model/Descriptor3} The populated <code>Descriptor3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Descriptor3();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Descriptor3.prototype.name = undefined;

