/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Descriptor10 model module.
 * @module model/Descriptor10
 * @version 1.0
 */
export class Descriptor10 {
  /**
   * Constructs a new <code>Descriptor10</code>.
   * @alias module:model/Descriptor10
   * @class
   * @param name {String} 
   * @param phone {String} 
   * @param email {String} 
   * @param code {String} 
   * @param symbol {String} 
   * @param shortDesc {String} 
   * @param longDesc {String} 
   * @param images {Object} 
   * @param audio {String} 
   * @param _3dRender {String} 
   */
  constructor(name, phone, email, code, symbol, shortDesc, longDesc, images, audio, _3dRender) {
    this.name = name;
    this.phone = phone;
    this.email = email;
    this.code = code;
    this.symbol = symbol;
    this.shortDesc = shortDesc;
    this.longDesc = longDesc;
    this.images = images;
    this.audio = audio;
    this._3dRender = _3dRender;
  }

  /**
   * Constructs a <code>Descriptor10</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Descriptor10} obj Optional instance to populate.
   * @return {module:model/Descriptor10} The populated <code>Descriptor10</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Descriptor10();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('shortDesc'))
        obj.shortDesc = ApiClient.convertToType(data['shortDesc'], 'String');
      if (data.hasOwnProperty('longDesc'))
        obj.longDesc = ApiClient.convertToType(data['longDesc'], 'String');
      if (data.hasOwnProperty('images'))
        obj.images = ApiClient.convertToType(data['images'], Object);
      if (data.hasOwnProperty('audio'))
        obj.audio = ApiClient.convertToType(data['audio'], 'String');
      if (data.hasOwnProperty('3d_render'))
        obj._3dRender = ApiClient.convertToType(data['3d_render'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Descriptor10.prototype.name = undefined;

/**
 * @member {String} phone
 */
Descriptor10.prototype.phone = undefined;

/**
 * @member {String} email
 */
Descriptor10.prototype.email = undefined;

/**
 * @member {String} code
 */
Descriptor10.prototype.code = undefined;

/**
 * @member {String} symbol
 */
Descriptor10.prototype.symbol = undefined;

/**
 * @member {String} shortDesc
 */
Descriptor10.prototype.shortDesc = undefined;

/**
 * @member {String} longDesc
 */
Descriptor10.prototype.longDesc = undefined;

/**
 * @member {Object} images
 */
Descriptor10.prototype.images = undefined;

/**
 * @member {String} audio
 */
Descriptor10.prototype.audio = undefined;

/**
 * @member {String} _3dRender
 */
Descriptor10.prototype._3dRender = undefined;

