/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Contact} from './Contact';
import {Location4} from './Location4';

/**
 * The End model module.
 * @module model/End
 * @version 1.0
 */
export class End {
  /**
   * Constructs a new <code>End</code>.
   * @alias module:model/End
   * @class
   * @param contact {module:model/Contact} 
   * @param location {module:model/Location4} 
   */
  constructor(contact, location) {
    this.contact = contact;
    this.location = location;
  }

  /**
   * Constructs a <code>End</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/End} obj Optional instance to populate.
   * @return {module:model/End} The populated <code>End</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new End();
      if (data.hasOwnProperty('contact'))
        obj.contact = Contact.constructFromObject(data['contact']);
      if (data.hasOwnProperty('location'))
        obj.location = Location4.constructFromObject(data['location']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Contact} contact
 */
End.prototype.contact = undefined;

/**
 * @member {module:model/Location4} location
 */
End.prototype.location = undefined;

