/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Provider} from './Provider';

/**
 * The Filterparams model module.
 * @module model/Filterparams
 * @version 1.0
 */
export class Filterparams {
  /**
   * Constructs a new <code>Filterparams</code>.
   * @alias module:model/Filterparams
   * @class
   * @param categories {Array.<String>} 
   * @param fulfillment {Array.<String>} 
   * @param minPrice {Number} 
   * @param maxPrice {Number} 
   * @param providers {Array.<module:model/Provider>} 
   */
  constructor(categories, fulfillment, minPrice, maxPrice, providers) {
    this.categories = categories;
    this.fulfillment = fulfillment;
    this.minPrice = minPrice;
    this.maxPrice = maxPrice;
    this.providers = providers;
  }

  /**
   * Constructs a <code>Filterparams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Filterparams} obj Optional instance to populate.
   * @return {module:model/Filterparams} The populated <code>Filterparams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Filterparams();
      if (data.hasOwnProperty('categories'))
        obj.categories = ApiClient.convertToType(data['categories'], ['String']);
      if (data.hasOwnProperty('fulfillment'))
        obj.fulfillment = ApiClient.convertToType(data['fulfillment'], ['String']);
      if (data.hasOwnProperty('minPrice'))
        obj.minPrice = ApiClient.convertToType(data['minPrice'], 'Number');
      if (data.hasOwnProperty('maxPrice'))
        obj.maxPrice = ApiClient.convertToType(data['maxPrice'], 'Number');
      if (data.hasOwnProperty('providers'))
        obj.providers = ApiClient.convertToType(data['providers'], [Provider]);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} categories
 */
Filterparams.prototype.categories = undefined;

/**
 * @member {Array.<String>} fulfillment
 */
Filterparams.prototype.fulfillment = undefined;

/**
 * @member {Number} minPrice
 */
Filterparams.prototype.minPrice = undefined;

/**
 * @member {Number} maxPrice
 */
Filterparams.prototype.maxPrice = undefined;

/**
 * @member {Array.<module:model/Provider>} providers
 */
Filterparams.prototype.providers = undefined;

