/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Customer} from './Customer';
import {End} from './End';

/**
 * The Fulfillment model module.
 * @module model/Fulfillment
 * @version 1.0
 */
export class Fulfillment {
  /**
   * Constructs a new <code>Fulfillment</code>.
   * @alias module:model/Fulfillment
   * @class
   * @param providerId {String} 
   * @param end {module:model/End} 
   * @param type {String} 
   * @param customer {module:model/Customer} 
   */
  constructor(providerId, end, type, customer) {
    this.providerId = providerId;
    this.end = end;
    this.type = type;
    this.customer = customer;
  }

  /**
   * Constructs a <code>Fulfillment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fulfillment} obj Optional instance to populate.
   * @return {module:model/Fulfillment} The populated <code>Fulfillment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Fulfillment();
      if (data.hasOwnProperty('provider_id'))
        obj.providerId = ApiClient.convertToType(data['provider_id'], 'String');
      if (data.hasOwnProperty('end'))
        obj.end = End.constructFromObject(data['end']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('customer'))
        obj.customer = Customer.constructFromObject(data['customer']);
    }
    return obj;
  }
}

/**
 * @member {String} providerId
 */
Fulfillment.prototype.providerId = undefined;

/**
 * @member {module:model/End} end
 */
Fulfillment.prototype.end = undefined;

/**
 * @member {String} type
 */
Fulfillment.prototype.type = undefined;

/**
 * @member {module:model/Customer} customer
 */
Fulfillment.prototype.customer = undefined;

