/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Address22} from './Address22';

/**
 * The Location5 model module.
 * @module model/Location5
 * @version 1.0
 */
export class Location5 {
  /**
   * Constructs a new <code>Location5</code>.
   * @alias module:model/Location5
   * @class
   * @param id {String} 
   * @param descriptor {String} 
   * @param gps {String} 
   * @param address {module:model/Address22} 
   * @param stationCode {String} 
   * @param city {String} 
   * @param country {String} 
   * @param circle {String} 
   * @param polygon {String} 
   * @param _3dspace {String} 
   */
  constructor(id, descriptor, gps, address, stationCode, city, country, circle, polygon, _3dspace) {
    this.id = id;
    this.descriptor = descriptor;
    this.gps = gps;
    this.address = address;
    this.stationCode = stationCode;
    this.city = city;
    this.country = country;
    this.circle = circle;
    this.polygon = polygon;
    this._3dspace = _3dspace;
  }

  /**
   * Constructs a <code>Location5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Location5} obj Optional instance to populate.
   * @return {module:model/Location5} The populated <code>Location5</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Location5();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('descriptor'))
        obj.descriptor = ApiClient.convertToType(data['descriptor'], 'String');
      if (data.hasOwnProperty('gps'))
        obj.gps = ApiClient.convertToType(data['gps'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = Address22.constructFromObject(data['address']);
      if (data.hasOwnProperty('stationCode'))
        obj.stationCode = ApiClient.convertToType(data['stationCode'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('circle'))
        obj.circle = ApiClient.convertToType(data['circle'], 'String');
      if (data.hasOwnProperty('polygon'))
        obj.polygon = ApiClient.convertToType(data['polygon'], 'String');
      if (data.hasOwnProperty('3dspace'))
        obj._3dspace = ApiClient.convertToType(data['3dspace'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Location5.prototype.id = undefined;

/**
 * @member {String} descriptor
 */
Location5.prototype.descriptor = undefined;

/**
 * @member {String} gps
 */
Location5.prototype.gps = undefined;

/**
 * @member {module:model/Address22} address
 */
Location5.prototype.address = undefined;

/**
 * @member {String} stationCode
 */
Location5.prototype.stationCode = undefined;

/**
 * @member {String} city
 */
Location5.prototype.city = undefined;

/**
 * @member {String} country
 */
Location5.prototype.country = undefined;

/**
 * @member {String} circle
 */
Location5.prototype.circle = undefined;

/**
 * @member {String} polygon
 */
Location5.prototype.polygon = undefined;

/**
 * @member {String} _3dspace
 */
Location5.prototype._3dspace = undefined;

