/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Criteria2} from './Criteria2';

/**
 * The Message3 model module.
 * @module model/Message3
 * @version 1.0
 */
export class Message3 {
  /**
   * Constructs a new <code>Message3</code>.
   * @alias module:model/Message3
   * @class
   * @param criteria {module:model/Criteria2} 
   */
  constructor(criteria) {
    this.criteria = criteria;
  }

  /**
   * Constructs a <code>Message3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Message3} obj Optional instance to populate.
   * @return {module:model/Message3} The populated <code>Message3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Message3();
      if (data.hasOwnProperty('criteria'))
        obj.criteria = Criteria2.constructFromObject(data['criteria']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Criteria2} criteria
 */
Message3.prototype.criteria = undefined;

