/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Catalog1} from './Catalog1';

/**
 * The Message6 model module.
 * @module model/Message6
 * @version 1.0
 */
export class Message6 {
  /**
   * Constructs a new <code>Message6</code>.
   * @alias module:model/Message6
   * @class
   * @param catalogs {Array.<module:model/Catalog1>} 
   * @param count {Number} 
   */
  constructor(catalogs, count) {
    this.catalogs = catalogs;
    this.count = count;
  }

  /**
   * Constructs a <code>Message6</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Message6} obj Optional instance to populate.
   * @return {module:model/Message6} The populated <code>Message6</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Message6();
      if (data.hasOwnProperty('catalogs'))
        obj.catalogs = ApiClient.convertToType(data['catalogs'], [Catalog1]);
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Catalog1>} catalogs
 */
Message6.prototype.catalogs = undefined;

/**
 * @member {Number} count
 */
Message6.prototype.count = undefined;

