/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OneOfFulfillment1Customer model module.
 * @module model/OneOfFulfillment1Customer
 * @version 1.0
 */
export class OneOfFulfillment1Customer {
  /**
   * Constructs a new <code>OneOfFulfillment1Customer</code>.
   * @alias module:model/OneOfFulfillment1Customer
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OneOfFulfillment1Customer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfFulfillment1Customer} obj Optional instance to populate.
   * @return {module:model/OneOfFulfillment1Customer} The populated <code>OneOfFulfillment1Customer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfFulfillment1Customer();
    }
    return obj;
  }
}
