/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Context9} from './Context9';
import {Message12} from './Message12';

/**
 * The Oninit model module.
 * @module model/Oninit
 * @version 1.0
 */
export class Oninit {
  /**
   * Constructs a new <code>Oninit</code>.
   * @alias module:model/Oninit
   * @class
   * @param context {module:model/Context9} 
   * @param message {module:model/Message12} 
   */
  constructor(context, message) {
    this.context = context;
    this.message = message;
  }

  /**
   * Constructs a <code>Oninit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Oninit} obj Optional instance to populate.
   * @return {module:model/Oninit} The populated <code>Oninit</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Oninit();
      if (data.hasOwnProperty('context'))
        obj.context = Context9.constructFromObject(data['context']);
      if (data.hasOwnProperty('message'))
        obj.message = Message12.constructFromObject(data['message']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Context9} context
 */
Oninit.prototype.context = undefined;

/**
 * @member {module:model/Message12} message
 */
Oninit.prototype.message = undefined;

