/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Billing} from './Billing';
import {Item3} from './Item3';
import {Payment} from './Payment';
import {Provider2} from './Provider2';
import {ProviderLocation} from './ProviderLocation';
import {Quote2} from './Quote2';

/**
 * The Order model module.
 * @module model/Order
 * @version 1.0
 */
export class Order {
  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   * @param quote {module:model/Quote2} 
   * @param provider {module:model/Provider2} 
   * @param providerLocation {module:model/ProviderLocation} 
   * @param payment {module:model/Payment} 
   * @param items {Array.<module:model/Item3>} 
   * @param billing {module:model/Billing} 
   */
  constructor(quote, provider, providerLocation, payment, items, billing) {
    this.quote = quote;
    this.provider = provider;
    this.providerLocation = providerLocation;
    this.payment = payment;
    this.items = items;
    this.billing = billing;
  }

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Order();
      if (data.hasOwnProperty('quote'))
        obj.quote = Quote2.constructFromObject(data['quote']);
      if (data.hasOwnProperty('provider'))
        obj.provider = Provider2.constructFromObject(data['provider']);
      if (data.hasOwnProperty('provider_location'))
        obj.providerLocation = ProviderLocation.constructFromObject(data['provider_location']);
      if (data.hasOwnProperty('payment'))
        obj.payment = Payment.constructFromObject(data['payment']);
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [Item3]);
      if (data.hasOwnProperty('billing'))
        obj.billing = Billing.constructFromObject(data['billing']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Quote2} quote
 */
Order.prototype.quote = undefined;

/**
 * @member {module:model/Provider2} provider
 */
Order.prototype.provider = undefined;

/**
 * @member {module:model/ProviderLocation} providerLocation
 */
Order.prototype.providerLocation = undefined;

/**
 * @member {module:model/Payment} payment
 */
Order.prototype.payment = undefined;

/**
 * @member {Array.<module:model/Item3>} items
 */
Order.prototype.items = undefined;

/**
 * @member {module:model/Billing} billing
 */
Order.prototype.billing = undefined;

