/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Params1 model module.
 * @module model/Params1
 * @version 1.0
 */
export class Params1 {
  /**
   * Constructs a new <code>Params1</code>.
   * @alias module:model/Params1
   * @class
   * @param amount {String} 
   * @param currency {String} 
   */
  constructor(amount, currency) {
    this.amount = amount;
    this.currency = currency;
  }

  /**
   * Constructs a <code>Params1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Params1} obj Optional instance to populate.
   * @return {module:model/Params1} The populated <code>Params1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Params1();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} amount
 */
Params1.prototype.amount = undefined;

/**
 * @member {String} currency
 */
Params1.prototype.currency = undefined;

