/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Params2} from './Params2';

/**
 * The Payment3 model module.
 * @module model/Payment3
 * @version 1.0
 */
export class Payment3 {
  /**
   * Constructs a new <code>Payment3</code>.
   * @alias module:model/Payment3
   * @class
   * @param uri {String} 
   * @param tlMethod {String} 
   * @param params {module:model/Params2} 
   * @param type {String} 
   * @param status {String} 
   * @param time {String} 
   */
  constructor(uri, tlMethod, params, type, status, time) {
    this.uri = uri;
    this.tlMethod = tlMethod;
    this.params = params;
    this.type = type;
    this.status = status;
    this.time = time;
  }

  /**
   * Constructs a <code>Payment3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Payment3} obj Optional instance to populate.
   * @return {module:model/Payment3} The populated <code>Payment3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Payment3();
      if (data.hasOwnProperty('uri'))
        obj.uri = ApiClient.convertToType(data['uri'], 'String');
      if (data.hasOwnProperty('tlMethod'))
        obj.tlMethod = ApiClient.convertToType(data['tlMethod'], 'String');
      if (data.hasOwnProperty('params'))
        obj.params = Params2.constructFromObject(data['params']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} uri
 */
Payment3.prototype.uri = undefined;

/**
 * @member {String} tlMethod
 */
Payment3.prototype.tlMethod = undefined;

/**
 * @member {module:model/Params2} params
 */
Payment3.prototype.params = undefined;

/**
 * @member {String} type
 */
Payment3.prototype.type = undefined;

/**
 * @member {String} status
 */
Payment3.prototype.status = undefined;

/**
 * @member {String} time
 */
Payment3.prototype.time = undefined;

