/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Quantity5 model module.
 * @module model/Quantity5
 * @version 1.0
 */
export class Quantity5 {
  /**
   * Constructs a new <code>Quantity5</code>.
   * @alias module:model/Quantity5
   * @class
   * @param count {Number} 
   * @param measure {String} 
   */
  constructor(count, measure) {
    this.count = count;
    this.measure = measure;
  }

  /**
   * Constructs a <code>Quantity5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Quantity5} obj Optional instance to populate.
   * @return {module:model/Quantity5} The populated <code>Quantity5</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Quantity5();
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
      if (data.hasOwnProperty('measure'))
        obj.measure = ApiClient.convertToType(data['measure'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} count
 */
Quantity5.prototype.count = undefined;

/**
 * @member {String} measure
 */
Quantity5.prototype.measure = undefined;

