/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Breakup2} from './Breakup2';
import {Price9} from './Price9';

/**
 * The Quote4 model module.
 * @module model/Quote4
 * @version 1.0
 */
export class Quote4 {
  /**
   * Constructs a new <code>Quote4</code>.
   * @alias module:model/Quote4
   * @class
   * @param price {module:model/Price9} 
   * @param breakup {Array.<module:model/Breakup2>} 
   * @param ttl {String} 
   */
  constructor(price, breakup, ttl) {
    this.price = price;
    this.breakup = breakup;
    this.ttl = ttl;
  }

  /**
   * Constructs a <code>Quote4</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Quote4} obj Optional instance to populate.
   * @return {module:model/Quote4} The populated <code>Quote4</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Quote4();
      if (data.hasOwnProperty('price'))
        obj.price = Price9.constructFromObject(data['price']);
      if (data.hasOwnProperty('breakup'))
        obj.breakup = ApiClient.convertToType(data['breakup'], [Breakup2]);
      if (data.hasOwnProperty('ttl'))
        obj.ttl = ApiClient.convertToType(data['ttl'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/Price9} price
 */
Quote4.prototype.price = undefined;

/**
 * @member {Array.<module:model/Breakup2>} breakup
 */
Quote4.prototype.breakup = undefined;

/**
 * @member {String} ttl
 */
Quote4.prototype.ttl = undefined;

