/*
 * sandbox-client-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Address14} from './Address14';

/**
 * The Updatebillingaddressrequest model module.
 * @module model/Updatebillingaddressrequest
 * @version 1.0
 */
export class Updatebillingaddressrequest {
  /**
   * Constructs a new <code>Updatebillingaddressrequest</code>.
   * @alias module:model/Updatebillingaddressrequest
   * @class
   * @param name {String} 
   * @param address {module:model/Address14} 
   * @param email {String} 
   * @param phone {String} 
   */
  constructor(name, address, email, phone) {
    this.name = name;
    this.address = address;
    this.email = email;
    this.phone = phone;
  }

  /**
   * Constructs a <code>Updatebillingaddressrequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Updatebillingaddressrequest} obj Optional instance to populate.
   * @return {module:model/Updatebillingaddressrequest} The populated <code>Updatebillingaddressrequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Updatebillingaddressrequest();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = Address14.constructFromObject(data['address']);
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Updatebillingaddressrequest.prototype.name = undefined;

/**
 * @member {module:model/Address14} address
 */
Updatebillingaddressrequest.prototype.address = undefined;

/**
 * @member {String} email
 */
Updatebillingaddressrequest.prototype.email = undefined;

/**
 * @member {String} phone
 */
Updatebillingaddressrequest.prototype.phone = undefined;

